debug: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffee_service
    username: postgres
    password: sch123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080